import {requireSupabase} from './supabase-client.js'; import {TABLES} from './constants.js';
const active=query=>query.is('deleted_at',null).eq('is_active',true);
export async function fetchProductsBySection(slug){const db=requireSupabase();const {data:{session}}=await db.auth.getSession();const isAdmin=!!session;const {data:section,error:sectionError}=await db.from(TABLES.sections).select('id,icon_name').eq('slug',slug).is('deleted_at',null).eq('is_active',true).single();if(sectionError)throw sectionError;if(section.icon_name==='library-book.svg'&&!isAdmin)throw new Error('Not authorized');const {data,error}=await active(db.from(TABLES.products).select('*, product_variants(*)').eq('section_id',section.id)).order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(product=>{const variants=(product.product_variants||[]).filter(v=>!v.deleted_at).sort((a,b)=>a.display_order-b.display_order);const prices=[product.base_price,...variants.map(v=>v.price_override??product.base_price)];return {...product,variants,has_different_prices:new Set(prices).size>1,starting_price:Math.min(...prices)}})}
export async function fetchProductDetails(id){const db=requireSupabase();const {data:{session}}=await db.auth.getSession();const isAdmin=!!session;const {data,error}=await active(db.from(TABLES.products).select('*, product_variants(*)').eq('id',id)).single();if(error)throw error;const {data:section}=await db.from(TABLES.sections).select('icon_name').eq('id',data.section_id).single();if(section&&section.icon_name==='library-book.svg'&&!isAdmin)throw new Error('Not authorized');return {...data,variants:(data.product_variants||[]).filter(v=>!v.deleted_at).sort((a,b)=>a.display_order-b.display_order)}}
export async function validateCartItems(items){if(!items.length)return new Map();const db=requireSupabase();const ids=items.map(item=>item.product_id);const {data,error}=await active(db.from(TABLES.products).select('id,product_variants(id,is_in_stock,deleted_at)').in('id',ids));if(error)throw error;const map=new Map();for(const item of items){const product=(data||[]).find(row=>row.id===item.product_id);const variant=product?.product_variants.find(row=>row.id===item.variant_id&&!row.deleted_at&&row.is_in_stock);map.set(item.variant_id,!variant)}return map}
async function syncVariants(productId,variants){const db=requireSupabase();const {data:old,error}=await db.from(TABLES.variants).select('id').eq('product_id',productId).is('deleted_at',null);if(error)throw error;const known=new Set(variants.filter(v=>v.id).map(v=>v.id));const removed=(old||[]).filter(v=>!known.has(v.id)).map(v=>v.id);if(removed.length){const {error:e}=await db.from(TABLES.variants).update({deleted_at:new Date().toISOString()}).in('id',removed);if(e)throw e}for(const [index,variant] of variants.entries()){const value={label:variant.label,price_override:variant.price_override||null,image_url:variant.image_url||null,is_in_stock:variant.is_in_stock!==false,display_order:index};const request=variant.id?db.from(TABLES.variants).update(value).eq('id',variant.id):db.from(TABLES.variants).insert({...value,product_id:productId});const {error:e}=await request;if(e)throw e}}
export async function createProduct(product,variants){const db=requireSupabase();const {data,error}=await db.from(TABLES.products).insert(product).select().single();if(error)throw error;await syncVariants(data.id,variants.length?variants:[{label:'افتراضي'}]);return fetchProductDetails(data.id)}
export async function updateProduct(id,updates,variants){const {error}=await requireSupabase().from(TABLES.products).update(updates).eq('id',id);if(error)throw error;await syncVariants(id,variants);return fetchProductDetails(id)}
export async function softDeleteProduct(id){const {error}=await requireSupabase().from(TABLES.products).update({deleted_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return true}
